name: Update docs when receiving repo dispatch
on:
  repository_dispatch:
    types: [updated]
jobs:
  run:
    name: Retrieve docs incrementally and deploy the website
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set known_hosts
        id: know-hosts
        run: |
          echo "::set-output name=BJ1::$(ssh-keyscan -H ${{ secrets.BJ_1_HOST }})"
          echo "::set-output name=BJ2::$(ssh-keyscan -H ${{ secrets.BJ_2_HOST }})"
          echo "::set-output name=LA1::$(ssh-keyscan -H ${{ secrets.LA_1_HOST }})"
          echo "::set-output name=LA2::$(ssh-keyscan -H ${{ secrets.LA_2_HOST }})"

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: |
            ${{ steps.know-hosts.outputs.BJ1 }}
            ${{ steps.know-hosts.outputs.BJ2 }}
            ${{ steps.know-hosts.outputs.LA1 }}
            ${{ steps.know-hosts.outputs.LA2 }}

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Restore yarn cache
        uses: actions/cache@v1
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
            ${{ runner.os }}-yarn-

      - name: Install deps
        run: yarn

      - name: Restore en-docs-dm-cache
        uses: actions/cache@v1
        id: en-docs-dm-cache
        with:
          path: ./markdown-pages/contents/en/docs-dm
          key: ${{ runner.os }}-en-docs-dm-cache-build-0
          restore-keys: |
            ${{ runner.os }}-en-docs-dm-cache-build-0

      - name: Check en-docs-dm-cache
        if: steps.en-docs-dm-cache.outputs.cache-hit != 'true'
        run: yarn download:docs-dm:all:en

      - name: Restore zh-docs-dm-cache
        uses: actions/cache@v1
        id: zh-docs-dm-cache
        with:
          path: ./markdown-pages/contents/zh/docs-dm
          key: ${{ runner.os }}-zh-docs-dm-cache-build-0
          restore-keys: |
            ${{ runner.os }}-zh-docs-dm-cache-build-0

      - name: Check zh-docs-dm-cache
        if: steps.zh-docs-dm-cache.outputs.cache-hit != 'true'
        run: yarn download:docs-dm:all:zh

      - name: Download docs based on dispatch payload
        run: yarn sync ${{ github.event.client_payload.repo }} ${{ github.event.client_payload.ref }} ${{ github.event.client_payload.sha }}

      - name: Restore gatsby cache
        uses: actions/cache@v1
        id: gatsby-cache
        with:
          path: ./.cache
          key: ${{ runner.os }}-gatsby-cache-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-gatsby-cache-${{ hashFiles('yarn.lock') }}
            ${{ runner.os }}-gatsby-cache-

      - name: Restore gatsby build
        uses: actions/cache@v1
        id: gatsby-build
        with:
          path: ./public
          key: ${{ runner.os }}-gatsby-build-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-gatsby-build-${{ hashFiles('yarn.lock') }}
            ${{ runner.os }}-gatsby-build-

      - name: Build website
        run: yarn build

      - name: Deploy
        run: |
          rsync -avz --delete public/ "${{ secrets.SSH_USER }}@${{ secrets.BJ_1_HOST }}:${{ secrets.DEPLOY_PATH }}"
          rsync -avz --delete public/ "${{ secrets.SSH_USER }}@${{ secrets.BJ_2_HOST }}:${{ secrets.DEPLOY_PATH }}"
